export const PLAYERS_LIST_REQUEST = "PLAYERS_LIST_REQUEST";
export const PLAYERS_LIST_SUCCESS = "PLAYERS_LIST_SUCCESS";
export const PLAYERS_LIST_FAIL = "PLAYERS_LIST_FAIL";

export const PLAYERS_DETAILS_FAIL = "PLAYERS_DETAILS_FAIL";
export const PLAYERS_DETAILS_REQUEST = "PLAYERS_DETAILS_REQUEST";
export const PLAYERS_DETAILS_SUCCESS = "PLAYERS_DETAILS_SUCCESS";
