# Generated by Django 3.2 on 2022-01-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220104_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='last_update',
        ),
    ]
