# Generated by Django 3.2 on 2022-01-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
