# Generated by Django 3.2 on 2022-01-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220119_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='total_points',
            new_name='avg_intex_rating',
        ),
        migrations.AddField(
            model_name='player',
            name='total_index_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
